travis:
  secure:
    BINSTAR_TOKEN: QP4xrtsjt9udgZY7NA1ipdy+VaWKGgdR5R8Cz+aNF/Co7jSdLb0uFCyfQOpPSTpblv6JollTjkbEm3BKwWGL4UgFzF3fk7g48+huieiFnxQoqDG+Cwzz2LWEsg3hJw2hfizkDgHR1zmgCWVZAvVWgfTMnucngvCHBo1dJXAyjidZw85zsdfkKvGiwEpXXKUN1PPxDelp6dH7U1hQguAf+OF2oQZdj4dIWWAdUKC9nC2cnCKPUqPV13GJcV27S+7JPeYs5TDMcVIMugM1kyDuO/+IbE1UAKP7PvzRk3cM7yhFMtDNCbcRwslbTAvOBpWQ5f7eBQV5PdntjRFiIWce3MmwpyMbli5cU3ElBdgXP5LnErABuwKV/qxq07N6EnyMnKGbODRWXhiadKuj6NADnOr5rfRw664Q76HGDwcXJGRPelajpqNvUfan1YjxP9CqtJ9bO9sIAUzXsX5wPQJtPv/8KMR46PgUY8sOZxcozhHWzG05oqvPsZYrDpLuu+mg3BPRWef5hbtYMkjlC2/62neDSw3hJ0gpKUqoMLtrT2mEu+rWQ4I29Nnxndn0+cDMZULIMaIukQQITPRJVImkGNpYsLWJI5VxmqZEC83f7CaNTeL4jxGPi2HSMe300xzsH4phiM5viUzZyeSDi+tUeQIVYy3BkxQL2gRPd4vkws0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
