travis:
  secure:
    BINSTAR_TOKEN: iTsE8gfx99QQWoqAiJKz7p0+38I6qpiuECO42irkxHRujYswoHw5oi5Ml91djxHirQitwakiEJtaPWRaLBoVoqyDLEFTOAza4xniqScgzMntdA0shyO3PJFFU/PUHI/sL7sh1k1zTa9VWV33hlKgSIlqT+OZOj6xohttSJ+u1Gb3UaaXHw+i2qXedkjNBzC3Chwa9Eqky5RXv8muGcXqwLuIyPmgQUPO6HUPhXZ4j8FojysMi3OmuN8OBQQvIG4JbcqqyAotSCgqOn1jQ8Gx/ba3ffjTlIjMflvm3EgJR7wnC2+I9V5hipYK+6PW6Tw422cY7txuwt3522kblYXuYVHdRgTYSWONpQ/PO7684WW4FqoKZoYFcH1KcmvW7vXV5eQ11wqGtVKcjIc1GnEnrwB/XfYaCCujiDIcUkQykfaZkWvAOzmLXALmGj7nnIX0U4C2+yPvn0uASpPeH2Nd6g2HOhsDwBjlpNnFPxbobEKXKqXpeIRwtNdQbi5bP13ixUTlnk29otlAHrMz81VPZrIE83NcEtvMey/Fd4kLrRUSvomIt669go23xp9p1E2ZRgrLhjApqtlB9q+GmsCPJGvZ3Ni46yAL3jBAqY5OorhI8FRd7BXgJ0STMUcLwKaGlXVPwy4KhOfJGFLRMfGsrB25vTxXW6vDUVwqlq/CcJM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
