travis:
  secure:
    BINSTAR_TOKEN: DHR6q4BAQa6OoeP01dgVp1slJbt42DSRKy+9xwLBu12PIVM5+/iHdkBVHAt69UFPFStCF+vz/XOCZKN5ZpjLxFfIwLD61+9o+3It2CFwrNQplEAoGoaZ6GkPfjvRg/SU41Jm9jaW60Ws4WOCG98uoPWddiMbAYIQJorGE3qw6tPSztnIZl4v4XwYeUmQGVl9gAUIYqW9wGwMBg9gMXBlUvwlLFE5fl58HUzfOS0xB0+KNkyKu/ux0ToHVEnV4zY1z0B5ZeYNDJohvRjLyivi7BSbpsBXnQ1onRbXFQzlFLCToaQvn7bkNRSum+qkJ7JaFkXHixBrKBbFlQEOOT8TYKzJr2hxNJ01v1aVOkUQFyryJdsoA1Y5PnSq5X484u/Jbp1zHdxMekfpudsiVwOl8Tv4E2pEyeeypv4UivKh0l7vNCKsovvVM5omydbrkXzbB4WmSRVlJiwhpmon38waIerY/Bdvm/uKBB1N5zA+blriBbVkMGUTzqpfK0t9afecDjmnIjJcGyaFDOGGi0EYRqUwFt2wbd4C80lfJx6bbo/jFVzoQ4pR1A8PeMuNbR3S0YoPhOt3B0ArUAF7J1WFvk1qhzuKkod0I1J65kAl9ZllsWisdzi13Yd5vEMWlo40yyfMBoIqlvegxjdR7hSVRmiZKG8PYulWZNGdx6B6TF8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
